
[[constraint]]
  name = "github.com/flachnetz/startup"
  version = "0.1.1"


[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"


[[override]]
  name = "golang.org/x/sys"
  revision = "d8f5ea21b9295e315e612b4bcf4bedea93454d4d"
